### ISSUE TITLE
HttpResponse content not rendered in distill-local

### ISSUE THREAD

**Issue by henhuy** [meeb/django-distill#25]
When using `distill-local` I became following error:
`django.template.response.ContentNotRenderedError: The response content must be rendered before it can be accessed.`
in line:
https://github.com/meeb/django-distill/blob/ea6132b6c21c73265c5b80389c9fb448c9eb7297/django_distill/renderer.py#L199
because `http_response`is not rendered yet.
After adding `http_response.render()` before that line, everything seems to work and distilled files are generated...
Is this fix correct?
I will post simple PR...

**Comment by meeb** [comment]
This is resolved by commit dedec26. Thanks for the issue and comments.
