### ISSUE TITLE
Google Backend Remote path on windows

### ISSUE THREAD

**Issue by JJMeijer** [meeb/django-distill#41]
Hi, I'm using django-distill with the Google storage backend on windows. When uploading a file the remote path for the file becomes `path\\to\\index.html`. However Google storage interprets that literally and does not convert the windows path format. So the URL for the uploaded file becomes `https://storage.googleapis.com/bucket/path%5Cto%5Cindex.html` instead of the `https://storage.googleapis.com/bucket/path/to/index.html` that you would expect.

Would it be possible to convert the windows-style path format to the right url format before initiating the upload?

**Comment by meeb** [comment]
I'm probably going to go with... probably not. Although maybe with testing, but even if possible it's probably not a great idea to build this into TubeSync as it's probably an upstream issue with the backend. What "Google storage backend" are you you actually using?

Effectively what TubeSync does internally is create the file path then pass it directly to `youtube-dl` as the "where to download the file to" output path, say `/media/videos/some-channel/somevideo.mkv` with `/media` mapped to your host somewhere. With your deployment I assume TubeSync would somehow need to pass in a path like `/media/videos/some-channel\\somevideo.mkv` or something with a hybrid mix of / and \ in the path... which would be a bit mad. This would also "break" some stuff in TubeSync as the file path stored locally in the TubeSync database and what TubeSync sees in the container would be flat and have no directories which would have some knock-on issues (e.g. some metadata writing that assume directories). The path of "file\file.mkv" is not in a directory in the container.

This must be an extremely common issue when doing whatever mapping it is you're doing, all containers (which are all Linux internally) are going to be using `/` as a directory separator, is there no general global setting for "map Linux style paths to URIs" in whatever tool you're using to map the Google Cloud bucket on your host machine?

On a side note, downloading videos from YouTube is probably a ToS violation of your Google account, so storing saved YouTube videos on a Google cloud product might not be a fantastic idea!

**Comment by meeb** [comment]
Interesting, the Google Clould Files API docs say they handle both `\` and `/` as directory separators, however I'll push a small patch to replace '\' with '/` anyway in remote paths when uploading with the bundled Google storage backend anyway.

**Comment by meeb** [comment]
This is in the just pushed 2.7 version if `django-distill` - please update and see if this fixes your issue. I don't actually have a Windows machine on hand (or a Google account!) to test this so I've just taken an educated guess to fix it.

**Comment by JJMeijer** [comment]
Fixed! Thank you and take care!

**Comment by meeb** [comment]
No problem, cheers!
