### ISSUE TITLE
distill-local  --force --collectstatic : asks for permission to collect static

### ISSUE THREAD

**Issue by julzhk** [meeb/django-distill#53]
This isn't a big deal but it's a little unexpected behaviour, so might be worth making a point in the documentation.

**Comment by meeb** [comment]
Thanks, a reasonable point. I've just added `--no-input` to the internal call to `collectstatic` from Distill. This will stop the `yes/no` confirmation question from being raised. Given `--collectstatic` is an opt-in flag to `distill-local` this is probably fine.
