### ISSUE TITLE
Broken link on site

### ISSUE THREAD

**Issue by robotichead** [meeb/django-distill#55]
Went to the installation page - https://django-distill.com/install . At the bottom of the page is the link to the intergration
![image](https://user-images.githubusercontent.com/12730065/168571988-05a9bd40-723e-4fa4-9f96-5e04d1c746e3.png)

Clicked on the link and it went to the following incorrect address; `https://django-distill.com/integration.html`. This address should be `https://django-distill.com/integration`

**Comment by meeb** [comment]
This issue was for the https://github.com/meeb/django-distill-site/ repo not this one, thanks for the heads up though, I've fixed the link just now.
