### ISSUE TITLE
how do i use django admin

### ISSUE THREAD

**Issue by ricardosmbr** [meeb/django-distill#63]
i need to use django admin
It's possible ?
this distill_path generates error 
 distill_path('',
                admin.site.urls,
                name=''),

**Comment by meeb** [comment]
Hi, I'm not entirely sure what you want to do here. Why do you want to create the static output of the Django admin page? If you just want to use the default admin CMS and have a statically rendered output site you can use the admin as normal (not wrap its URLs in `distill_path`) and that will work fine.

See here:

https://github.com/meeb/django-distill-example/blob/master/demoblog/urls.py

and here:

https://github.com/meeb/django-distill-example/blob/master/blog/urls.py

as an example.

**Comment by meeb** [comment]
I'll close this for now, but feel free to comment if you have any additional questions.
